In [1]:
import torch
import torch.nn as nn
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [3]:
pear_padded = torch.tensor([17, 5, 1, 19], dtype=torch.float32) # e.g., "pear"
ace_padded = torch.tensor([1, 3, 5, 0], dtype=torch.float32)    # e.g., "ace"
h_padded = torch.tensor([8, 0, 0, 0], dtype=torch.float32)      # e.g., "h"

padded_tensor = torch.stack([pear_padded, ace_padded, h_padded])

describe(padded_tensor)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[17.,  5.,  1., 19.],
        [ 1.,  3.,  5.,  0.],
        [ 8.,  0.,  0.,  0.]])


In [4]:
lengths = [4, 3, 1]
packed_tensor = pack_padded_sequence(padded_tensor, lengths, batch_first=True)
packed_tensor

PackedSequence(data=tensor([17.,  1.,  8.,  5.,  3.,  1.,  5., 19.]), batch_sizes=tensor([3, 2, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [5]:
unpacked_tensor, unpacked_lengths = pad_packed_sequence(packed_tensor, batch_first=True)
describe(unpacked_tensor)
describe(unpacked_lengths)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[17.,  5.,  1., 19.],
        [ 1.,  3.,  5.,  0.],
        [ 8.,  0.,  0.,  0.]])
Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([4, 3, 1])
